require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ImagesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Image. As you add validations to Admin::Image, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all admin_images as @admin_images" do
      image = Admin::Image.create! valid_attributes
      get :index
      assigns(:admin_images).should eq([image])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_image as @admin_image" do
      image = Admin::Image.create! valid_attributes
      get :show, :id => image.id.to_s
      assigns(:admin_image).should eq(image)
    end
  end

  describe "GET new" do
    it "assigns a new admin_image as @admin_image" do
      get :new
      assigns(:admin_image).should be_a_new(Admin::Image)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_image as @admin_image" do
      image = Admin::Image.create! valid_attributes
      get :edit, :id => image.id.to_s
      assigns(:admin_image).should eq(image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Image" do
        expect {
          post :create, :admin_image => valid_attributes
        }.to change(Admin::Image, :count).by(1)
      end

      it "assigns a newly created admin_image as @admin_image" do
        post :create, :admin_image => valid_attributes
        assigns(:admin_image).should be_a(Admin::Image)
        assigns(:admin_image).should be_persisted
      end

      it "redirects to the created admin_image" do
        post :create, :admin_image => valid_attributes
        response.should redirect_to(Admin::Image.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_image as @admin_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Image.any_instance.stub(:save).and_return(false)
        post :create, :admin_image => {}
        assigns(:admin_image).should be_a_new(Admin::Image)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Image.any_instance.stub(:save).and_return(false)
        post :create, :admin_image => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_image" do
        image = Admin::Image.create! valid_attributes
        # Assuming there are no other admin_images in the database, this
        # specifies that the Admin::Image created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Image.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => image.id, :admin_image => {'these' => 'params'}
      end

      it "assigns the requested admin_image as @admin_image" do
        image = Admin::Image.create! valid_attributes
        put :update, :id => image.id, :admin_image => valid_attributes
        assigns(:admin_image).should eq(image)
      end

      it "redirects to the admin_image" do
        image = Admin::Image.create! valid_attributes
        put :update, :id => image.id, :admin_image => valid_attributes
        response.should redirect_to(image)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_image as @admin_image" do
        image = Admin::Image.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Image.any_instance.stub(:save).and_return(false)
        put :update, :id => image.id.to_s, :admin_image => {}
        assigns(:admin_image).should eq(image)
      end

      it "re-renders the 'edit' template" do
        image = Admin::Image.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Image.any_instance.stub(:save).and_return(false)
        put :update, :id => image.id.to_s, :admin_image => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_image" do
      image = Admin::Image.create! valid_attributes
      expect {
        delete :destroy, :id => image.id.to_s
      }.to change(Admin::Image, :count).by(-1)
    end

    it "redirects to the admin_images list" do
      image = Admin::Image.create! valid_attributes
      delete :destroy, :id => image.id.to_s
      response.should redirect_to(admin_images_url)
    end
  end

end
